server:
  port: 8080
spring:
  application:
    name: "service-bookstore"
  r2dbc:
    url: "r2dbc:h2:file:///./database/bookstore"
    username: sa
    password:
    pool:
      enabled: true
      max-size: 2
      initial-size: 2
  messages:
    basename: i18n/application
    encoding: UTF-8
  sql:
    init:
      mode: always
      schema-locations: classpath:ddl/v1.sql
logging:
  level:
    org.springframework.r2dbc.core.DefaultDatabaseClient: debug